Update scripttest.yml

diff --git a/.github/workflows/scripttest.yml b/.github/workflows/scripttest.yml
--- a/.github/workflows/scripttest.yml
+++ b/.github/workflows/scripttest.yml
@@ -15,6 +15,7 @@ jobs:
         if ($STATUS -match "pass") 
         {
           echo "pass"
+          exit 1
         } 
         else 
         {
@@ -38,7 +39,23 @@ jobs:
         ACTIONS_KEY: ${{ secrets.ACTIONS_KEY }}
         echo "Service User Name: $ACTIONS_KEY"
        
-       
+  job2:
+   runs-on: windows-latest
+   needs: job1
+   steps: 
+     - name: Trigger the Workflow in auto gatling execution Repository2       
+       run: |
+        $STATUS = 'pass'     
+        echo "The status of application is: $STATUS" 
+        if ($STATUS -match "pass") 
+        {
+          echo "pass"
+        } 
+        else 
+        {
+          echo "fail"
+        }    
+        
          
      
               
